// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyoemmawgbxmbaeahfrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5b2VtbWF3Z2J4bWJhZWFoZnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5Nzg3OTcsImV4cCI6MjA1MDU1NDc5N30.rDXyqFIbiRcQXUKnWgInLZ6KoP05N4fHObPoGpbHtdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);